[package]
name = "rspim"
version = "0.1.0"
authors = ["insou22 <zac.kologlu@gmail.com>"]
edition = "2018"

[lib]
name = "rspim_lib"
path = "src/lib.rs"

[[bin]]
name = "rspim"
path = "src/bin/bin.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }  # for data deserialization
serde_yaml = "0.8"                                  #   - see mips.yaml
strsim = "0.10.0"   # for error-reporting - string similarity