name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        experimental: [false]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose --package mipsy

    - name: Install SPIM
      run: |
        svn checkout svn://svn.code.sf.net/p/spimsimulator/code/ spimsimulator-code
        cd spimsimulator-code/spim
        make PREFIX=..
        make test

    - name: Test
      run: bash ${{ github.workspace }}/scripts/compare.sh
